Feat/GitHub actions
americanexpress/css-to-js pull request #12
Opened 2021-06-17 15:13 UTC by nellyk

2021-06-17 16:00 UTC, JAdshead approved these changes, later dismissed

2021-06-25 18:33 UTC, JAdshead commented on .github/workflows/tests.yml
> +        node: [ '12.x', '14.x', '16.x' ]
current test target 10, 12 and 14 so we should probably stick to that
```suggestion
        node: [ '10.x', '12.x', '14.x' ]
```

2021-10-30 01:32 UTC, 10xLaCroixDrinker requested changes

2021-10-30 01:32 UTC, 10xLaCroixDrinker commented on .github/workflows/health-check.yml
> +        node: [ '10.x', '12.x', '14.x' ]
```suggestion
        node: [ '10.x', '12.x', '14.x', '16.x' ]
```

2021-10-30 01:32 UTC, 10xLaCroixDrinker commented on .github/workflows/release.yml
> +          node-version: 12
```suggestion
          node-version: 16
```

2021-10-30 01:32 UTC, 10xLaCroixDrinker commented on .github/workflows/tests.yml
> +        node: [ '10.x', '12.x', '14.x' ]
```suggestion
        node: [ '10.x', '12.x', '14.x', '16.x' ]
```

2021-10-30 01:36 UTC, 10xLaCroixDrinker approved these changes

2021-11-04 14:51 UTC, eddhurst approved these changes

2021-11-04 14:59 UTC, merged