fix(bin): updated filename
americanexpress/css-to-js pull request #4
Opened 2020-03-17 19:43 UTC by ksliao

2020-03-17 19:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/americanexpress/css-to-js?pullRequest=4) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/americanexpress/css-to-js?pullRequest=4) before we can accept your contribution.<br/><hr/>**Katrina S Liao** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/americanexpress/css-to-js?pullRequest=4) it.</sub>

2020-03-17 19:58 UTC, 10xLaCroixDrinker submitted a review, later dismissed

2020-03-17 20:18 UTC, anescobar1991 commented
@ksliao did this fix your issue?!?!

2020-03-17 20:21 UTC, anescobar1991 requested changes
Unit tests are failing on travis

2020-03-18 00:35 UTC, JamesSingleton approved these changes

2020-03-18 15:35 UTC, anescobar1991 approved these changes

2020-03-18 15:35 UTC, merged